---
packages:
  - openssh-client          # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop
  - python3-apt             # python-apt required by Ansible
  - python3-dev             # python-dev required by ambari agent
  - libssl-dev              # openssl-devel recommended for Ranger KMS
  - libtirpc-dev            # libtirpc required by HDP 2.6+
  - openjdk-8-jdk

chrony_path: /etc/
chrony_service: chronyd
firewall_service_name: ufw
