---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: (ansible_os_family|lower == "redhat") or (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 12)

- name: Restart ambari-agent
  service:
    name: ambari-agent
    state: restarted
