---
packages:
  - openssh-clients         # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - chrony                  # ntp required by Hadoop
#  - openssl-devel           # openssl-devel recommended for Ranger KMS | too manly conflict with installed packages
  - libtirpc-devel          # libtirpc required by HDP 2.6+
  - libselinux-python       # libselinux-python required by Ansible
  - perf
  - sysstat
  - tcpdump
  - dstat
  - net-tools
  - expect
  - rpm-python
  - psmisc
  - java-1.8.0-openjdk-devel

ntp_service_name: chronyd

firewall_service_name: firewalld

versioned_packages:
  - {pkg_name: "openssl-libs openssl openssl-devel", version: "1.0.2k-19.el7"}
  - {pkg_name: "krb5-libs", version: "1.15.1-50.el7"}
  - {pkg_name: "zlib zlib-devel", version: "1.2.7-18.el7"}
  - {pkg_name: "python python-libs", version: "2.7.5-89.el7"}
