---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower | replace(' ', '_')}}.yml"
        - defaults.yml
      paths:
        - ../database/vars

- name: Fail if trying to install MariaDB on unsupported OS
  fail:
    msg: "MariaDB is not available or supported on SLES 11 and Debian/Ubuntu"
  when: database == "mariadb" and ((ansible_os_family|lower == "suse" and ansible_distribution_major_version|int == 11) or ansible_os_family|lower == "debian")


- name: Install "{{ database }}" database packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ hostvars[inventory_hostname][database + '_packages'] | join(',') }}"


- name: Include database setup
  include_tasks: database.yml
  when: database != "embedded" and not database_options.external_hostname|default('')