- name: ensure /opt/ exist
  file:
    path: /opt/
    state: directory
    mode: '0755'

- name: copy jdk to opt
  copy:
    src: "{{ trino_jdk_archive }}"
    dest: "/opt/"
    mode: '0644'
  register: copy_result

- name: unarchive jdk
  unarchive:
    src: "/opt/{{ trino_jdk_archive | basename }}"
    dest: /opt/
    remote_src: yes