- name: 确保/opt/目录存在
  file:
    path: /opt/
    state: directory
    mode: '0755'

- name: 从变量指定的位置复制JDK压缩包到目标机器
  copy:
    src: "{{ trino_jdk_archive }}"
    dest: "/opt/"
    mode: '0644'
  register: copy_result

- name: 解压JDK压缩包到/opt/
  unarchive:
    src: "/opt/{{ jdk_archive | basename }}"
    dest: /opt/
    remote_src: yes
  when: copy_result.changed