---

- name: create the ambari_run_user group or verify if its present
  group:
    name: "{{ambari_options.ambari_run_user}}"
    state: present

- name: create user ambari_run_user
  user:
    name: "{{ambari_options.ambari_run_user}}"
    shell: /bin/bash
    groups: "{{ambari_options.ambari_run_user}}"
    append: yes

- name: Copy RPM files to remote host
  copy:
    src: "{{ item }}"
    dest: "/tmp"
  loop: "{{ lookup('fileglob', '*.rpm', wantlist=True) }}"

- name: Install copied RPM packages
  yum:
    name: "/tmp/{{ item }}"
    state: present
  loop: "{{ lookup('fileglob', '*.rpm', wantlist=True) | map('basename') | list }}"
  when: ansible_os_family | lower == "redhat" and  ansible_distribution_major_version | int == 7

- name: Install the ambari-agent package
  package:
    name: ambari-agent
    update_cache: yes
    state: latest
  notify: Reload systemd

- name: set run_user for Ambari agents
  replace:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "run_as_user=root"
    replace: "run_as_user={{ambari_options.ambari_run_user}}"
    backup: no

- name: Set the Ambari Server in the agent configuration
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname="
    line: "hostname={{ hostvars[groups['ambari-server']|first]['ansible_fqdn'] }}"
    state: present
  notify: Restart ambari-agent


### The following is done on Python >= 2.7 to prevent issues with the latest Python libraries rejecting lower TLS protocols
- name: Configure the Ambari Agents to use TLS 1.2
  ini_file:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    create: no
    section: "security"
    option: "force_https_protocol"
    value: "PROTOCOL_TLSv1_2"
    state: present
  notify: Restart ambari-agent
  when: (ansible_python_version is version_compare('2.7.9', '>=') and ansible_os_family|lower == "debian") or
        (ansible_python_version is version_compare('2.7', '>=') and ((ansible_os_family|lower == "redhat" and ansible_distribution_major_version|int >= 7) or
                                                                     (ansible_os_family|lower == "suse" and ansible_distribution_major_version|int >= 12) or
                                                                     (ansible_os_family|lower == "redhat" and ansible_distribution|lower == "amazon")))

- name: Update ambari-agent log dir
  ini_file:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    create: no
    section: "agent"
    option: "logdir"
    value: "{{ base_log_dir }}/ambari-agent"
    state: present
  notify: Restart ambari-agent

- meta: flush_handlers

- name: Make sure the ambari-agent service is started
  service:
    name: ambari-agent
    state: started

- name: Make sure the ambari-agent service is enabled
  service:
    name: ambari-agent
    enabled: yes
  ignore_errors: true
