---
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../ambari-blueprint/vars

#- block:
#    - name: Get the VersionDefinition id from Ambari (Ambari >= 2.6)
#      uri:
#        url: "http://{{ ansible_fqdn }}:8080/api/v1/version_definitions?VersionDefinition/release/version={{ (install_hdp|default(false) == true) | ternary(hdp_version,hdf_version) }}"
#        method: GET
#        force_basic_auth: yes
#        user: "{{ ambari_admin_user }}"
#        password: "{{ ambari_admin_password }}"
#        headers: '{"X-Requested-By":"ambari"}'
#        status_code: 200,201,202
#        return_content: yes
#      register: version_definition
#
#    - name: Fail if could not get a VersionDefinition from Ambari
#      fail:
#        msg: "Could not get the VersionDefinition from Ambari. The following is the received information from Ambari: {{ version_definition }}"
#      when: (version_definition.content|from_yaml)['items'] | length == 0
#
#    - name: Set the VersionDefinition id (Ambari >= 2.6)
#      set_fact:
#        vdf_id: "{{ (version_definition.content|from_yaml)['items'][0]['VersionDefinition']['id'] }}"
#  when: ambari_version is version_compare('2.6', '>=')

- name: Check if a cluster {{ cluster_name }} already exists
  uri:
    url: "http://{{ ansible_fqdn }}:8080/api/v1/clusters/{{ cluster_name }}"
    method: GET
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    status_code: 200,201,202,404
  register: cluster_check

- name: Fail if a cluster {{ cluster_name }} already exists
  fail:
    msg: Cluster {{ cluster_name }} already exists!
  when: cluster_check.status != 404

- name: Generate the cluster static blueprint
  set_fact:
    cluster_blueprint: "{{ lookup('file', 'blueprint.json', convert_data=False) }}"

- name: Print the cluster blueprint
  debug:
    var: cluster_blueprint
    verbosity: 1

- name: Generate the cluster creation template
  set_fact:
    cluster_template: "{{ lookup('file', 'cluster_template.json', convert_data=False) }}"

- name: Print the cluster creation template
  debug:
    var: cluster_template
    verbosity: 1

- name: Delete any existing blueprint called {{ blueprint_name }}
  uri:
    url: "http://{{ ansible_fqdn }}:8080/api/v1/blueprints/{{ blueprint_name }}"
    method: DELETE
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    status_code: 200,201,202,404
    return_content: no
  when: cluster_check.status == 404

- name: Upload the blueprint {{ blueprint_name }} to the Ambari server
  uri:
    url: "http://{{ ansible_fqdn }}:8080/api/v1/blueprints/{{ blueprint_name }}"
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: "{{ cluster_blueprint|to_json }} "
    body_format: raw
    status_code: 200,201,202,409
    timeout: 60
    return_content: no

- name: "Modify the  base_url repository for bigtop stack"
  uri:
    url: http://{{ ansible_fqdn }}:8080/api/v1/stacks/BIGTOP/versions/3.2.0/operating_systems/redhat7/repositories/BIGTOP-3.2.0
    method: PUT
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: " {\"Repositories\" : { \"repo_name\": \"bigtop\", \"base_url\" : \"http://172.27.8.22:8081/repository/yum/sdp_3.1\", \"verify_base_url\": true } }"
    body_format: raw
    status_code: 200,201,202
    return_content: no

- name: Launch the create cluster request
  uri:
    url: http://{{ ansible_fqdn }}:8080/api/v1/clusters/{{ cluster_name }}
    method: POST
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari"}'
    body: "{{ cluster_template|to_json }} "
    body_format: raw
    status_code: 200,201,202
    timeout: 120
    return_content: yes
  register: cluster_create_task

- name: Wait for the cluster to be built
  uri:
    url: "{{ (cluster_create_task.content|from_json).href }}"
    force_basic_auth: yes
    user: "{{ ambari_options.ambari_admin_user }}"
    password: "{{ ambari_options.ambari_admin_password }}"
    headers: '{"X-Requested-By":"ambari", "Content-Type":"application/json"}'
    status_code: 200,201,202
    return_content: yes
  register: cluster_check_task
  until: (((cluster_check_task.content|from_json).Requests.request_status == 'COMPLETED' and (cluster_check_task.content|from_json).Requests.completed_task_count|int > 0) or
         (cluster_check_task.content|from_json).Requests.request_status == 'FAILED' or
         (cluster_check_task.content|from_json).Requests.request_status == 'TIMEDOUT' or
         (cluster_check_task.content|from_json).Requests.request_status == 'ABORTED')
  retries: "{{ wait_timeout // 10 }}"
  delay: 10
  when: wait and cluster_create_task is defined and cluster_create_task

- name: Fail if the cluster create task is in an error state
  fail:
    msg: "Failed to build the {{ cluster_name }} cluster. Task Status is {{ (cluster_check_task.content|from_json).Requests.request_status }}."
  when: wait and ((cluster_check_task.content|from_json).Requests.request_status == 'FAILED' or
         (cluster_check_task.content|from_json).Requests.request_status == 'TIMEDOUT' or
         (cluster_check_task.content|from_json).Requests.request_status == 'ABORTED')
