
# Generated by CodiumAI

from ci_tools.python.install_utils.conf_refactor import BaseConfiguration

import pytest

class TestBaseConfiguration:

    #  can load configuration from file
    def test_load_configuration_from_file(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")
        conf = config.get_conf()

        assert conf == {"key1": "value1", "key2": "value2"}

    #  can get a specific key from configuration
    def test_get_specific_key_from_configuration(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")
        conf = config.get("key1")

        assert conf == "value1"

    #  can set configuration
    def test_set_configuration(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")
        config.set_conf({"key1": "new_value1", "key2": "new_value2"})
        conf = config.get_conf()

        assert conf == {"key1": "new_value1", "key2": "new_value2"}

    #  raises error when loading non-existent configuration file
    def test_raises_error_when_loading_non_existent_configuration_file(self):
        conf_loader = DefaultConfigurationLoader
        name = "non_existent_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")

        with pytest.raises(FileNotFoundError):
            config.get_conf()

    #  raises error when setting non-dictionary configuration
    def test_raises_error_when_setting_non_dictionary_configuration(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")

        with pytest.raises(ValueError):
            config.set_conf("invalid_config")

    #  raises error when getting non-existent key from configuration
    def test_raises_error_when_getting_non_existent_key_from_configuration(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")

        with pytest.raises(InvalidConfigurationException):
            config.get("non_existent_key")

    #  can save configuration to file
    def test_save_configuration_to_file(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")
        config.set_conf({"key1": "value1", "key2": "value2"})
        config.save()

        file_path = os.path.join("/path/to/config", name)
        assert os.path.exists(file_path)

        with open(file_path, 'r') as file:
            content = file.read()
            assert content == "key1: value1\nkey2: value2\n"

    #  can get configuration as string
    def test_get_configuration_as_string(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.YAML)
        config.set_path("/path/to/config")
        config.set_conf({"key1": "value1", "key2": "value2"})
        str_conf = config.get_str_conf()

        assert str_conf == "key1: value1\nkey2: value2\n"

    #  can set file format
    def test_set_file_format(self):
        conf_loader = DefaultConfigurationLoader
        name = "example_config.yaml"

        config = BaseConfiguration(name, conf_loader)
        config.set_format(FileManager.FileType.JSON)

        assert config.format == FileManager.FileType.JSON
