
# Generated by CodiumAI

from ci_tools.python.install_utils.conf_refactor import FileManager

import pytest

class TestFileManager:

    #  FileManager can read a raw file and return its content as a string
    def test_read_raw_file(self):
        file_path = "example.txt"
        file_type = FileManager.FileType.RAW

        data = "This is an example file."

        FileManager.write_file(file_path, data, file_type)

        read_data = FileManager.read_file(file_path, file_type)

        assert read_data == data

    #  FileManager can read a JSON file and return its content as a dictionary
    def test_read_json_file(self):
        file_path = "example.json"
        file_type = FileManager.FileType.JSON

        data = {"key": "value"}

        FileManager.write_file(file_path, data, file_type)

        read_data = FileManager.read_file(file_path, file_type)

        assert read_data == data

    #  FileManager can read a YAML file and return its content as a dictionary
    def test_read_yaml_file(self):
        file_path = "example.yaml"
        file_type = FileManager.FileType.YAML

        data = {"key": "value"}

        FileManager.write_file(file_path, data, file_type)

        read_data = FileManager.read_file(file_path, file_type)

        assert read_data == data

    #  FileManager raises a ValueError if an unsupported file type is passed as an argument
    def test_unsupported_file_type(self):
        file_path = "example.txt"
        file_type = "unsupported"

        with pytest.raises(ValueError):
            FileManager.read_file(file_path, file_type)

    #  FileManager raises an exception if there is an error while loading a JSON file
    def test_error_loading_json_file(self):
        file_path = "example.json"
        file_type = FileManager.FileType.JSON

        data = "invalid json"

        FileManager.write_file(file_path, data, file_type)

        with pytest.raises(Exception):
            FileManager.read_file(file_path, file_type)

    #  FileManager raises an exception if there is an error while loading a YAML file
    def test_error_loading_yaml_file(self):
        file_path = "example.yaml"
        file_type = FileManager.FileType.YAML

        data = "invalid yaml"

        FileManager.write_file(file_path, data, file_type)

        with pytest.raises(Exception):
            FileManager.read_file(file_path, file_type)
