
# Generated by CodiumAI

from ci_tools.python.install_utils.conf_refactor import DefaultConfigurationLoader

import pytest

class TestDefaultConfigurationLoader:

    #  Loads a configuration file in YAML format successfully
    def test_load_yaml_file_successfully(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.YAML)
        conf_name = "test.yaml"
        expected_content = {"key": "value"}
        with open(os.path.join(CONF_DIR, conf_name), 'w') as file:
            yaml.dump(expected_content, file)
        content = conf_loader.load_conf(conf_name)
        assert content == expected_content

    #  Loads a configuration file in JSON format successfully
    def test_load_json_file_successfully(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.JSON)
        conf_name = "test.json"
        expected_content = {"key": "value"}
        with open(os.path.join(CONF_DIR, conf_name), 'w') as file:
            json.dump(expected_content, file)
        content = conf_loader.load_conf(conf_name)
        assert content == expected_content

    #  Loads a configuration file in RAW format successfully
    def test_load_raw_file_successfully(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.RAW)
        conf_name = "test.txt"
        expected_content = "This is a test"
        with open(os.path.join(CONF_DIR, conf_name), 'w') as file:
            file.write(expected_content)
        content = conf_loader.load_conf(conf_name)
        assert content == expected_content

    #  Raises FileNotFoundError when the configuration file does not exist
    def test_raises_file_not_found_error(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.YAML)
        conf_name = "nonexistent.yaml"
        with pytest.raises(FileNotFoundError):
            conf_loader.load_conf(conf_name)

    #  Raises ValueError when an unsupported file type is provided
    def test_raises_value_error_for_unsupported_file_type(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.JSON)
        conf_name = "test.txt"
        with pytest.raises(ValueError):
            conf_loader.load_conf(conf_name)

    #  Returns the content of the configuration file as a string
    def test_returns_content_as_string(self):
        conf_loader = DefaultConfigurationLoader(CONF_DIR, FileManager.FileType.YAML)
        conf_name = "test.yaml"
        expected_content = {"key": "value"}
        with open(os.path.join(CONF_DIR, conf_name), 'w') as file:
            yaml.dump(expected_content, file)
        content = conf_loader.load_conf(conf_name)
        assert isinstance(content, str)
        assert content == yaml.dump(expected_content)
