- name: install ntpd
  yum:
    name: ntp
    state: present

- name: scp ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: copy script to master
  template:
    src: ntp.server.conf.j2
    dest: /etc/ntp.conf
  when: ntp_server_hostname | default('') != '' and inventory_hostname in groups['ambari-server']

- name: start ntp
  systemd:
    name: ntpd
    state: restarted
    enabled: yes
    daemon_reload: yes
  ignore_errors: True

- name: restart crontab service
  service:
    name: crond
    state: restarted
    enabled: yes

#强制进行同步
- name: crontab ntp
  shell: '/usr/sbin/ntpdate -u {{ntp_server_hostname}} && /sbin/hwclock -w'
  ignore_errors: True

#设置定时任务强制进行同步
- name: crontab ntp
  shell: 'echo "30 0 * * * /usr/sbin/ntpdate -u {{ntp_server_hostname}} && /sbin/hwclock -w" >> /var/spool/cron/root'
